version: "3"

services:
  theia-python:
    restart: always
    build: .
    image: theia-python
    container_name: theia-python-container
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ".:/home/workspace"
